---

- name: update all packages
  yum: name=* state=latest

- name: deploy profile-mark.sh
  copy: src=profile-mark.sh dest=/etc/profile.d/mark.sh owner=root group=root mode=0644

- name: selinux is a pain in the ass
  selinux: policy=targeted state=permissive

- name: deploy sudoers.d-rundeck
  copy: src=sudoers.d-rundeck dest=/etc/sudoers.d/rundeck owner=root group=root mode=0440
